const xml = `
    <codAdministrativo>${args.codAdministrativo}</codAdministrativo>
    <codigo_servico>${args.codigo_servico}</codigo_servico>
    <cartao>${args.cartao}</cartao>
    <destinatario>
      <nome>${args.destinatario.nome}</nome>
      <logradouro>${args.destinatario.logradouro}</logradouro>
      <numero>${args.destinatario.numero}</numero>
      <complemento>${args.destinatario.complemento}</complemento>
      <bairro>${args.destinatario.bairro}</bairro>
      <referencia>${args.destinatario.referencia}</referencia>
      <cidade>${args.destinatario.cidade}</cidade>
      <uf>${args.destinatario.uf}</uf>
      <cep>${args.destinatario.cep}</cep>
      <ddd>${args.destinatario.ddd}</ddd>
      <telefone>${args.destinatario.telefone}</telefone>
      <email>${args.destinatario.email}</email>
      <ciencia_conteudo_proibido>${args.destinatario.ciencia_conteudo_proibido}</ciencia_conteudo_proibido>
    </destinatario>
    <coletas_solicitadas>
      <tipo>${args.coletas_solicitadas.tipo}</tipo>
      <id_cliente>${args.coletas_solicitadas.id_cliente}</id_cliente>
      <valor_declarado>${args.coletas_solicitadas.valor_declarado}</valor_declarado>
      <descricao>${args.coletas_solicitadas.descricao}</descricao>
      <cklist>${args.coletas_solicitadas.cklist}</cklist>
      <documento>${args.coletas_solicitadas.documento}</documento>
      <remetente>
        <nome>${args.coletas_solicitadas.remetente.nome}</nome>
        <logradouro>${args.coletas_solicitadas.remetente.logradouro}</logradouro>
        <numero>${args.coletas_solicitadas.remetente.numero}</numero>
        <complemento>${args.coletas_solicitadas.remetente.complemento}</complemento>
        <bairro>${args.coletas_solicitadas.remetente.bairro}</bairro>
        <referencia>${args.coletas_solicitadas.remetente.referencia}</referencia>
        <cidade>${args.coletas_solicitadas.remetente.cidade}</cidade>
        <uf>${args.coletas_solicitadas.remetente.uf}</uf>
        <cep>${args.coletas_solicitadas.remetente.cep}</cep>
        <ddd>${args.coletas_solicitadas.remetente.ddd}</ddd>
        <telefone>${args.coletas_solicitadas.remetente.telefone}</telefone>
        <email>${args.coletas_solicitadas.remetente.email}</email>
        <identificacao>${args.coletas_solicitadas.remetente.identificacao}</identificacao>
        <ddd_celular>${args.coletas_solicitadas.remetente.ddd_celular}</ddd_celular>
        <celular>${args.coletas_solicitadas.remetente.celular}</celular>
        <sms>${args.coletas_solicitadas.remetente.sms}</sms>
        <restricao_anac>${args.coletas_solicitadas.remetente.restricao_anac}</restricao_anac>
      </remetente>
      <produto>
        <codigo>${args.coletas_solicitadas.produto.codigo}</codigo>
        <tipo>${args.coletas_solicitadas.produto.tipo}</tipo>
        <qtd>${args.coletas_solicitadas.produto.qtd}</qtd>
      </produto>
      <numero>${args.coletas_solicitadas.numero}</numero>
      <ag>${args.coletas_solicitadas.ag}</ag>
      <cartao>${args.coletas_solicitadas.cartao}</cartao>
      <servico_adicional>${args.coletas_solicitadas.servico_adicional}</servico_adicional>
      <ar>${args.coletas_solicitadas.ar}</ar>
      <obj_col>
        <item>${args.coletas_solicitadas.obj_col.item}</item>
        <desc>${args.coletas_solicitadas.obj_col.desc}</desc>
        <entrega>${args.coletas_solicitadas.obj_col.entrega}</entrega>
        <num>${args.coletas_solicitadas.obj_col.num}</num>
        <id>${args.coletas_solicitadas.obj_col.id}</id>
      </obj_col>
    </coletas_solicitadas>
`;
